// src/Commands/Core/MemberCard.js
const { createCanvas, loadImage } = require('canvas');
const axios = require('axios');
const fs = require('fs');
const path = require('path');
const { resolveTargetUser } = require('../../Helpers/mention');

module.exports = {
    name: 'membercard',
    aliases: ['mcard'],
    category: 'core',
    description: 'Create a personalized member card',
    exp: 15,
    cool: 10,
    react: '🪪',
    usage: '.mcard [@user | reply]',

    async execute(client, arg, M) {
        try {
            // Resolve target via helper (reply / @mention / id)
            const target = await resolveTargetUser(client, M, arg);

            let user = M.from;
            let targetId = M.from.id;

            if (target && target.id) {
                user = {
                    id: target.id,
                    first_name: target.first_name,
                    last_name: target.last_name,
                    username: target.username,
                };
                targetId = target.id;
            } else if (target?._unresolved) {
                return client.sendMessage(
                    M.chat.id,
                    `❌ Could not resolve @${target.username}. They must be registered with the bot, or reply to their message instead.`,
                    { parse_mode: 'Markdown' }
                );
            }

            // Get user details - Use first name for the card
            const firstName = user.first_name || 'User';
            const lastName = user.last_name || '';
            const fullName = lastName ? `${firstName} ${lastName}` : firstName;
            const username = user.username ? `@${user.username}` : firstName;
            
            console.log(`Creating member card for: ${fullName} (ID: ${targetId})`);

            // Send processing message
            const processingMsg = await client.sendMessage(M.chat.id, 
                `🔄 Creating member card for ${firstName}...`, 
                { parse_mode: 'Markdown' }
            );

            // Create the member card
            const imageBuffer = await createMemberCard(client, targetId, firstName, fullName);
            
            // Send the image
            await client.sendPhoto(M.chat.id, imageBuffer, {
                caption: `🎴 *Member Card for ${firstName}*\nGenerated by ZeroTwo. `,
                parse_mode: 'Markdown'
            });

            // Delete processing message
            await client.deleteMessage(M.chat.id, processingMsg.message_id);

        } catch (err) {
            console.error('Member card error:', err);
            await client.sendMessage(M.chat.id, 
                `❌ Error creating member card: ${err.message}`, 
                { parse_mode: 'Markdown' }
            );
        }
    }
};

async function createMemberCard(client, userId, firstName, fullName) {
    try {
        // Use LOCAL template image from assets folder
        const templatePath = path.join(__dirname, '../../../assets/images/sanomanjiro.jpg');
        
        // Check if file exists
        if (!fs.existsSync(templatePath)) {
            throw new Error(`Template image not found at: ${templatePath}`);
        }
        
        console.log('Loading template from local file:', templatePath);
        
        // Image dimensions (from your specifications)
        const IMAGE_WIDTH = 4096;
        const IMAGE_HEIGHT = 2932;
        
        // Rectangle coordinates for username (from your specifications)
        const rectX1 = 2080;
        const rectY1 = 1562;
        const rectX2 = 3460;
        const rectY2 = 1841;
        
        // Calculate rectangle dimensions
        const rectWidth = rectX2 - rectX1;
        const rectHeight = rectY2 - rectY1;
        
        // Text position - LEFT ALIGNED with padding
        const textX = rectX1 + 40; // 40px padding from left
        const textY = rectY1 + (rectHeight / 2); // Center vertically
        
        // Circle coordinates for profile picture (from your specifications)
        // Coordinates: (1209, 751) to (1209, 2228)
        const circleCenterX = 1209;
        const circleCenterY = 1489.5; // Midpoint of 751 and 2228: (751+2228)/2 = 1489.5
        const circleRadius = 738.5; // Half the height difference: (2228-751)/2 = 738.5

        // Create canvas
        const canvas = createCanvas(IMAGE_WIDTH, IMAGE_HEIGHT);
        const ctx = canvas.getContext('2d');

        // Load template image from LOCAL file (much faster!)
        const templateImg = await loadImage(templatePath);
        
        // Draw template
        ctx.drawImage(templateImg, 0, 0, IMAGE_WIDTH, IMAGE_HEIGHT);

        // Try to get and add profile picture using client methods
        try {
            console.log(`Fetching profile photo for user ${userId}...`);
            
            // Use your client's getUserProfilePhotos method
            const photos = await client.getUserProfilePhotos(Number(userId), { offset: 0, limit: 1 });
            
            if (photos.total_count > 0 && photos.photos && photos.photos.length > 0) {
                console.log('Profile photo found, loading...');
                
                // Get the largest available photo (last one in the array)
                const photo = photos.photos[0];
                const largestPhoto = photo[photo.length - 1];
                
                // Get file information
                const file = await client.getFile(largestPhoto.file_id);
                
                if (file && file.file_path) {
                    // Construct the file URL
                    const fileUrl = `https://api.telegram.org/file/bot${client.bot.token}/${file.file_path}`;
                    console.log('Profile photo URL:', fileUrl);
                    
                    // Download profile picture
                    const profileResponse = await axios.get(fileUrl, { 
                        responseType: 'arraybuffer',
                        timeout: 10000 
                    });
                    
                    const profileBuffer = Buffer.from(profileResponse.data);
                    const profileImg = await loadImage(profileBuffer);
                    
                    // Create circular clipping path for profile picture
                    ctx.save();
                    ctx.beginPath();
                    ctx.arc(circleCenterX, circleCenterY, circleRadius, 0, Math.PI * 2, true);
                    ctx.closePath();
                    ctx.clip();
                    
                    // Draw profile picture within the circle
                    const profileSize = circleRadius * 2;
                    
                    // Calculate position to center the image in the circle
                    const profileX = circleCenterX - circleRadius;
                    const profileY = circleCenterY - circleRadius;
                    
                    ctx.drawImage(
                        profileImg, 
                        0, 0, profileImg.width, profileImg.height, // Source dimensions
                        profileX, profileY, // Destination position
                        profileSize, profileSize // Destination size
                    );
                    
                    ctx.restore();
                    console.log('Profile picture added successfully');
                } else {
                    console.log('Could not get file path');
                    drawDefaultProfilePicture(ctx, circleCenterX, circleCenterY, circleRadius, firstName);
                }
            } else {
                console.log('No profile picture found for user');
                drawDefaultProfilePicture(ctx, circleCenterX, circleCenterY, circleRadius, firstName);
            }
        } catch (profileErr) {
            console.log('Profile picture error:', profileErr.message);
            drawDefaultProfilePicture(ctx, circleCenterX, circleCenterY, circleRadius, firstName);
        }

        // Add user's first name text to the rectangle - LEFT ALIGNED
        ctx.save();
        
        // Set text properties - LEFT ALIGNED
        ctx.fillStyle = '#FFFFFF'; // White text
        ctx.textAlign = 'left'; // Changed from 'center' to 'left'
        ctx.textBaseline = 'middle';
        
        // Calculate font size based on rectangle dimensions
        let fontSize = Math.min(rectHeight * 0.6, 150); // 60% of rectangle height, max 150px
        fontSize = Math.max(fontSize, 40); // Minimum 40px
        
        // Set font
        ctx.font = `bold ${fontSize}px Arial`;
        
        // Add text shadow for better readability
        ctx.shadowColor = 'rgba(0, 0, 0, 0.7)';
        ctx.shadowBlur = 10;
        ctx.shadowOffsetX = 2;
        ctx.shadowOffsetY = 2;
        
        // Use first name for the card
        const displayName = firstName;
        
        // Check if text fits in the rectangle (accounting for left padding)
        const textMetrics = ctx.measureText(displayName);
        const maxTextWidth = rectWidth - 80; // 80px total padding (40px each side)
        let finalName = displayName;
        
        if (textMetrics.width > maxTextWidth) {
            // Text is too wide, try to shorten it
            let shortenedName = displayName;
            while (shortenedName.length > 3 && ctx.measureText(shortenedName + '...').width > maxTextWidth) {
                shortenedName = shortenedName.slice(0, -1);
            }
            finalName = shortenedName + '...';
        }
        
        // Draw the name text - LEFT ALIGNED
        ctx.fillText(finalName, textX, textY);
        
        // Add a subtle stroke for better visibility
        ctx.strokeStyle = '#000000';
        ctx.lineWidth = 3;
        ctx.strokeText(finalName, textX, textY);
        
        ctx.restore();

        // Convert canvas to buffer
        console.log('Converting canvas to buffer...');
        const buffer = canvas.toBuffer('image/jpeg', { 
            quality: 0.95,
            progressive: true 
        });
        
        console.log('Member card created successfully!');
        return buffer;

    } catch (err) {
        console.error('Error creating member card:', err);
        throw err;
    }
}

function drawDefaultProfilePicture(ctx, centerX, centerY, radius, name) {
    console.log('Drawing default profile picture...');
    
    // Create a gradient for the circle background
    const gradient = ctx.createRadialGradient(
        centerX, centerY, radius * 0.3,
        centerX, centerY, radius
    );
    gradient.addColorStop(0, '#4F46E5'); // Indigo
    gradient.addColorStop(1, '#7C3AED'); // Purple
    
    // Draw circle background
    ctx.save();
    ctx.beginPath();
    ctx.arc(centerX, centerY, radius, 0, Math.PI * 2, true);
    ctx.closePath();
    ctx.fillStyle = gradient;
    ctx.fill();
    ctx.restore();
    
    // Add initial letter in the center
    ctx.save();
    ctx.fillStyle = '#FFFFFF';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    
    // Use the first letter of the name
    const initial = name.charAt(0).toUpperCase();
    const fontSize = radius * 1.2; // Size based on circle radius
    
    ctx.font = `bold ${fontSize}px Arial`;
    ctx.shadowColor = 'rgba(0, 0, 0, 0.5)';
    ctx.shadowBlur = 10;
    ctx.shadowOffsetX = 2;
    ctx.shadowOffsetY = 2;
    
    ctx.fillText(initial, centerX, centerY);
    ctx.restore();
}