const axios = require('axios');

module.exports = {
    name: 'aimage',
    aliases: ['animeai', 'aigen'],
    category: 'ai',
    description: 'Generate anime images with AI',
    usage: '.aimage <prompt>',
    
    async execute(client, arg, M) {
        try {
            const chatId = M.chat.id;
            
            // Check if user provided prompt
            if (!arg.trim()) {
                return client.sendMessage(chatId,
                    '🎨 *Anime AI Image Generator*\n\n' +
                    'Generate anime-style images with AI\n\n' +
                    'Usage: `.aimage <prompt>`\n' +
                    'Example: `.aimage cute cat girl in forest`\n' +
                    'Example: `.aimage cyberpunk city night`',
                    { parse_mode: 'Markdown' }
                );
            }
            
            const prompt = arg.trim();
            
            // Direct API call
            const apiUrl = `https://apis.prexzyvilla.site/ai/anime?prompt=${encodeURIComponent(prompt)}&negative_prompt?=`;
            
            // Send the image directly
            try {
                await client.sendPhoto(chatId, apiUrl, {
                    caption: '_Generated by ZeroTwo_'
                });
            } catch (error) {
                // If photo fails, try as document
                try {
                    await client.sendDocument(chatId, apiUrl, {
                        caption: '_Generated by ZeroTwo_'
                    });
                } catch (docError) {
                    await client.sendMessage(chatId,
                        '❌ Failed to generate image.\n' +
                        'Try a different prompt.',
                        { parse_mode: 'Markdown' }
                    );
                }
            }
            
        } catch (error) {
            console.error('AImage command error:', error);
            // Silent fail - don't send error message
        }
    }
};